fundacion/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('listar/', views.Listar, name = 'listar_noticias'),
]

fundacion/fundacion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Base, name = 'base'),

    # URLS de APPS
    path('Noticias/', include('apps.noticias.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fundacion/apps/noticias/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    titulo = models.CharField(max_length=120)
    creado = models.DateField(auto_now_add=True)
    cuerpo = models.TextField()
    autor = models.CharField(max_length=50, null=True, blank=True)
    imagen = models.ImageField(upload_to='noticias', null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.titulo

fundacion/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    pass

fundacion/apps/noticias/views.py
from django.shortcuts import render

from .models import Noticia
# Create your views here.

def Listar(request):
    # Crear el diccionario para pasar datos al template
    ctx = {}
    # Buscar las noticias en la base de datos
    # Pasarlo al template

    todas = Noticia.objects.all()
    ctx['notis'] = todas
    
    return render(request, 'noticias/listar_noticias.html', ctx)

fundacion/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

fundacion/fundacion/views.py
from django.shortcuts import render

def Base(request):
    return render(request, 'base.html')

fundacion/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>BDA Chaco Resistencia</title>

	<meta name="description" content="Practica para el proyecto de informatorio">
	<meta name="keywords" content="reducir, reciclar, reutilizar">

	<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css"/> <!--Estilos general-->
	<link rel="icon" type="image/x-icon" href="{% static 'img/rrr_ico.ico' %}"/>
</head>

<body>
<header>
	<div class="container">
		<div class="logo_header"><img src="{% static 'img/png_lg.png' %}"></div>
		<div class="menu">
			
			<ul>
				<li><a href="{% url 'base' %}">Inicio</a></li>
				<li><a href="{% url 'noticias:listar_noticias' %}">Noticias</a></li>
				<li><a href="#about_us">Nosotros</a></li>
				<li><a href="#contact_us">Contactos</a></li>
			</ul>

		</div>
	</div>
</header><!--fin header-->

<section>
	<div class="index_content">
		<div class="content_margin">
			
			<a href="#"><div class="outstanding">
				<div id="img_news"></div>
				<div id="title_news">Acá se manda el titular de la noticia más actual</div>
			</div></a><!--noticias destacadas, esto se tiene que repetir solo-->

		</div>
	</div>
</section> <!--fin section-->
	
<section>
	
</section> <!--nosotros-->

<section>
	
</section> <!--contacto-->
</body>
</html>